apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: outline
  annotations:
    keel.sh/policy: minor
    keel.sh/trigger: poll
  name: outline
  namespace: outline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outline
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: outline
    spec:
      containers:
        - image: docker.getoutline.com/outlinewiki/outline:latest
          name: outline
          ports:
            - containerPort: 3000
          env:
          - name: URL
            value: https://outline.ryzen.me
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: outline-postgresql-app
                key: uri
          - name: SMTP_FROM_EMAIL
            value: outline@ryzen.me
          - name: LOG_LEVEL
            value: info
          - name: REDIS_URL 
            value: redis://outline-redis:6379
          - name: FORCE_HTTPS
            value: "false"
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: outline-secret
                key: SECRET_KEY
          - name: UTILS_SECRET
            valueFrom:
              secretKeyRef:
                name: outline-secret
                key: UTILS_SECRET
          # keycloak authentication
          - name: OIDC_ISSUER_UR
            value: "https://auth.ryzen.me/realms/master"
          - name: OIDC_CLIENT_ID
            value: keycloak
          - name: OIDC_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: outline-secret
                key: OIDC_CLIENT_SECRET
          volumeMounts:
            - name: outline
              mountPath: /var/lib/outline/data
      volumes:
        - name: outline
          persistentVolumeClaim:
            claimName: outline-pvc
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: outline-redis
  annotations:
    keel.sh/policy: minor
    keel.sh/trigger: poll
  name: outline-redis
  namespace: outline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outline-redis
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: outline-redis
    spec:
      containers:
        - image: redis:latest
          name: outline-redis
          ports:
            - containerPort: 6379
      restartPolicy: Always