replicaCount: 1

image:
  repository: docker.getoutline.com/outlinewiki/outline
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: traefik
  annotations: {}
  host: ""
  path: /
  pathType: Prefix
  tls:
    secretName: ""

redis:
  enabled: true

storage:
  s3:
    enabled: true
    region: us-east-1
    pathStyle: true
  storageClassName: ""
  size: 10Gi

oidc:
  enabled: true
  issuerUrl: ""
  clientId: outline
  secret:
    name: outline-secret
    existing: false
    clientSecretKeyRef: OIDC_CLIENT_SECRET
    clientSecret: ""